version: 0.0
os: linux
files:
  - source: /Cloud_Food_Bolt/target/original-Food_Bolt-0.0.1-SNAPSHOT.jar
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: Server/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Server/stop_application
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Server/start_application
      timeout: 120
      runas: root
      
