#!/bin/bash
#nohup java -jar /tmp/original-Food_Bolt-0.0.1-SNAPSHOT.jar --server.port=8080 & > /dev/null 2>&1
#sleep 30
java -jar /tmp/original-Food_Bolt-0.0.1-SNAPSHOT.jar --server.port=8080 > /dev/null 2>&1 &
